### ISSUE TITLE
cider-nrepl hangs while resolving class that's not in the CLASSPATH

### ISSUE THREAD

**Issue by tsdh** [clojure-emacs/cider-nrepl#129]
I use a Java library in my clojure project which contains several custom classes derived from org.apache.tools.ant.Task which are only needed for building that lib itself or for building other programs that use this lib. However, they are not needed nor referenced at runtime neither by my clojure code nor by classes my clojure code uses.  But still, (during eldoc and company completion) I get hangs and my `*nrepl-server <project-name>*` shows this backtrace:

````
java.lang.NoClassDefFoundError: org/apache/tools/ant/Task
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:340)
    at clojure.lang.RT.classForName(RT.java:2110)
    at clojure.lang.Compiler.maybeResolveIn(Compiler.java:7017)
    at clojure.core$ns_resolve.invoke(core.clj:4177)
    at clojure.core$ns_resolve.invoke(core.clj:4174)
    at cider.nrepl.middleware.info$resolve_special.invoke(info.clj:71)
    at cider.nrepl.middleware.info$info_clj.invoke(info.clj:107)
    at cider.nrepl.middleware.info$info.invoke(info.clj:132)
    at cider.nrepl.middleware.info$eldoc.invoke(info.clj:240)
    at cider.nrepl.middleware.info$eldoc_reply.invoke(info.clj:246)
    at cider.nrepl.middleware.info$wrap_info$fn__2497.invoke(info.clj:261)
    at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
    at cider.nrepl.middleware.macroexpand$wrap_macroexpand$fn__2707.invoke(macroexpand.clj:79)
    at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
    at cider.nrepl.middleware.undef$wrap_undef$fn__3217.invoke(undef.clj:30)
    at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
    at cider.nrepl.middleware.classpath$wrap_classpath$fn__1245.invoke(classpath.clj:25)
    at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
    at cider.nrepl.middleware.apropos$wrap_apropos$fn__1178.invoke(apropos.clj:102)
    at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
    at cider.nrepl.middleware.complete$wrap_complete$fn__1994.invoke(complete.clj:47)
    at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
    at cider.nrepl.middleware.trace$wrap_trace$fn__3190.invoke(trace.clj:35)
    at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
    at cider.nrepl.middleware.resource$wrap_resource$fn__2769.invoke(resource.clj:25)
    at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
    at cider.nrepl.middleware.ns$wrap_ns$fn__2743.invoke(ns.clj:61)
    at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
    at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:19)
    at clojure.tools.nrepl.server$handle$fn__760.invoke(server.clj:28)
    at clojure.core$binding_conveyor_fn$fn__4241.invoke(core.clj:1912)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.tools.ant.Task
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 52 more
````

Since those `Task`-derived classes aren't used by me it seems that something loads all classes in CLASSPATH?

**Comment by cichli** [comment]
Possibly related are the comments further down on clojure-emacs/cider#879. I'm going to take a look and see if it's still occurring on the current snapshot this evening.

**Comment by cichli** [comment]
Of course `NoClassDefFoundError` doesn't inherit from `Exception` :-).
