### ISSUE TITLE
cider-nrepl hangs while resolving a specific class that actually exists in the CLASSPATH

### ISSUE THREAD

**Issue by tsdh** [clojure-emacs/cider-nrepl#130]
In one of my projects that use a certain Java library I get frequent hangs (mostly during eldoc or company completion).  After such a hang, my `*nrepl-server <project-name>*` buffer shows this exception:

````
/home/horn/.m2/repository/de/uni-koblenz/ist/jgralab/7.7.16/jgralab-7.7.16.jar(de/uni_koblenz/jgralab/greql/funlib/FunLib.java):64: error: cannot access Function
import de.uni_koblenz.jgralab.greql.funlib.Function.Category;
                                          ^
  bad source file: /home/horn/.m2/repository/de/uni-koblenz/ist/jgralab/7.7.16/jgralab-7.7.16.jar(de/uni_koblenz/jgralab/greql/funlib/Function.java)
    file does not contain class de.uni_koblenz.jgralab.greql.funlib.Function
    Please remove or make sure it appears in the correct subdirectory of the sourcepath.
ERROR: Unhandled REPL handler exception processing message {:op eldoc, :session 69d9c75b-9500-4b12-8a18-6235c3aba05d, :ns cobus2.utils, :symbol .get, :id 351}
com.sun.tools.javac.util.Abort
    at com.sun.tools.javac.comp.Check.completionError(Check.java:287)
    at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:615)
    at com.sun.tools.javac.comp.Attr.attribImportQualifier(Attr.java:445)
    at com.sun.tools.javac.comp.MemberEnter.visitImport(MemberEnter.java:544)
    at com.sun.tools.javac.tree.JCTree$JCImport.accept(JCTree.java:571)
    at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:437)
    at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:449)
    at com.sun.tools.javac.comp.MemberEnter.visitTopLevel(MemberEnter.java:528)
    at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:518)
    at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:437)
    at com.sun.tools.javac.comp.MemberEnter.complete(MemberEnter.java:1046)
    at com.sun.tools.javac.code.Symbol.complete(Symbol.java:574)
    at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1037)
    at com.sun.tools.javac.comp.Enter.complete(Enter.java:493)
    at com.sun.tools.javac.comp.Enter.main(Enter.java:471)
    at com.sun.tools.javadoc.JavadocEnter.main(JavadocEnter.java:78)
    at cider.nrepl.middleware.util.java.parser$parse_java.invoke(parser.clj:77)
    at cider.nrepl.middleware.util.java.parser$source_info.invoke(parser.clj:256)
    at clojure.lang.Var.invoke(Var.java:379)
    at cider.nrepl.middleware.util.java$class_info_STAR_.invoke(java.clj:145)
    at cider.nrepl.middleware.util.java$class_info.invoke(java.clj:182)
    at cider.nrepl.middleware.util.java$member_info.invoke(java.clj:214)
    at cider.nrepl.middleware.util.java$resolve_member$fn__2340.invoke(java.clj:261)
    at clojure.core$map$fn__4345.invoke(core.clj:2614)
    at clojure.lang.LazySeq.sval(LazySeq.java:40)
    at clojure.lang.LazySeq.seq(LazySeq.java:49)
    at clojure.lang.RT.seq(RT.java:484)
    at clojure.core$seq.invoke(core.clj:135)
    at clojure.core$filter$fn__4372.invoke(core.clj:2669)
    at clojure.lang.LazySeq.sval(LazySeq.java:40)
    at clojure.lang.LazySeq.seq(LazySeq.java:56)
    at clojure.lang.RT.seq(RT.java:484)
    at clojure.lang.RT.nthFrom(RT.java:893)
    at clojure.lang.RT.nth(RT.java:852)
    at clojure.core$distinct$step__4844$fn__4845$fn__4847.invoke(core.clj:4769)
    at clojure.core$distinct$step__4844$fn__4845.invoke(core.clj:4769)
    at clojure.lang.LazySeq.sval(LazySeq.java:40)
    at clojure.lang.LazySeq.seq(LazySeq.java:49)
    at clojure.lang.Cons.next(Cons.java:39)
    at clojure.lang.RT.countFrom(RT.java:585)
    at clojure.lang.RT.count(RT.java:575)
    at cider.nrepl.middleware.util.java$resolve_symbol.invoke(java.clj:283)
    at cider.nrepl.middleware.info$info_clj.invoke(info.clj:115)
    at cider.nrepl.middleware.info$info.invoke(info.clj:132)
    at cider.nrepl.middleware.info$eldoc.invoke(info.clj:240)
    at cider.nrepl.middleware.info$eldoc_reply.invoke(info.clj:246)
    at cider.nrepl.middleware.info$wrap_info$fn__2497.invoke(info.clj:261)
    at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
    at cider.nrepl.middleware.macroexpand$wrap_macroexpand$fn__2707.invoke(macroexpand.clj:79)
    at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
    at cider.nrepl.middleware.undef$wrap_undef$fn__3217.invoke(undef.clj:30)
    at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
    at cider.nrepl.middleware.classpath$wrap_classpath$fn__1245.invoke(classpath.clj:25)
    at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
    at cider.nrepl.middleware.apropos$wrap_apropos$fn__1178.invoke(apropos.clj:102)
    at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
    at cider.nrepl.middleware.complete$wrap_complete$fn__1994.invoke(complete.clj:47)
    at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
    at cider.nrepl.middleware.trace$wrap_trace$fn__3190.invoke(trace.clj:35)
    at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
    at cider.nrepl.middleware.resource$wrap_resource$fn__2769.invoke(resource.clj:25)
    at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
    at cider.nrepl.middleware.ns$wrap_ns$fn__2743.invoke(ns.clj:61)
    at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
    at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:19)
    at clojure.tools.nrepl.server$handle$fn__760.invoke(server.clj:28)
    at clojure.core$binding_conveyor_fn$fn__4241.invoke(core.clj:1912)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
````

I've checked jgralab-7.7.16.jar and it actually contains both `de/uni_koblenz/jgralab/greql/funlib/Function.java` and `de/uni_koblenz/jgralab/greql/funlib/Function.class`, so the error message seems to be wrong.

Maybe this line in the error message indicates the culprit:

````java
import de.uni_koblenz.jgralab.greql.funlib.Function.Category;
                                          ^
````

`de.uni_koblenz.jgralab.greql.funlib.Function` is an abstract class that contains a public `enum Category`.  (See https://github.com/jgralab/jgralab/blob/master/src/de/uni_koblenz/jgralab/greql/funlib/Function.java)

**Comment by hrathod** [comment]
I am also experiencing this problem with the latest git version of prelude.  I also ran updated all the packages using package-list-packages.
