### ISSUE TITLE
Thread timeout when loaded from OSGI-bundle

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/cider-nrepl#141]
Hello, I am tryng to embed cider-nrepl in Counterclockwise and I have encountered a problem (I cut the lines that I think are important):

    !ENTRY org.eclipse.osgi 2 0 2015-01-30 12:21:02.269
    !MESSAGE While loading class "clojure.asm.Type", thread "Thread[clojure-agent-send-off-pool-0,6,main]" timed out waiting (5009ms) for thread "Thread[main,6,main]" to finish starting bundle "ccw.core_0.31.2.qualifier [1097]". To avoid deadlock, thread "Thread[clojure-agent-send-off-pool-0,6,main]" is proceeding but "clojure.asm.Type" may not be fully initialized.
    !STACK 0
    org.osgi.framework.BundleException: State change in progress for bundle "reference:file:/home/kapitan/git/ccw/ccw.core/" by thread "main".
    at org.eclipse.osgi.framework.internal.core.AbstractBundle.beginStateChange(AbstractBundle.java:1088)
    at org.eclipse.osgi.framework.internal.core.AbstractBundle.start(AbstractBundle.java:298)
    at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:478)
    ....
    Caused by: org.eclipse.osgi.framework.internal.core.AbstractBundle$BundleStatusException
    	... 43 more
    Root exception:
    org.eclipse.osgi.framework.internal.core.AbstractBundle$BundleStatusException
    	at org.eclipse.osgi.framework.internal.core.AbstractBundle.beginStateChange(AbstractBundle.java:1088)
    ...
    at java.lang.Class.forName0(Native Method)
	    at java.lang.Class.forName(Class.java:191)
	    at cider.nrepl.middleware.util.java$class_info_STAR_$fn__2168.invoke(java.clj:141)
	    at cider.nrepl.middleware.util.java$class_info_STAR_.invoke(java.clj:141)
	    at cider.nrepl.middleware.util.java$class_info.invoke(java.clj:182)
	    at cider.nrepl.middleware.util.java$eval2205$fn__2206.invoke(java.clj:293)
	    at clojure.core$binding_conveyor_fn$fn__4407.invoke(core.clj:1912)
	    at clojure.lang.AFn.call(AFn.java:18)

I have got two of those:
```To avoid deadlock, thread "Thread[clojure-agent-send-off-pool-0,6,main]" is proceeding but "clojure.asm.Type" may not be fully initialized.```
 ```To avoid deadlock, thread "Thread[clojure-agent-send-off-pool-0,6,main]" is proceeding but "clojure.reflect.JavaReflector" may not be fully initialized.```

The complete patch is [here](https://github.com/arichiardi/ccw/commit/6542815e0d456ec9978dc3e0a31c4c65834189cf) while the initialization fn of cider-nrepl starts on [line 47](https://github.com/arichiardi/ccw/blob/6542815e0d456ec9978dc3e0a31c4c65834189cf/ccw.core/src/clj/ccw/core/launch.clj#L47). Nothing too weird I guess there. What can I do to properly init cider-nrepl?

**Comment by arichiardi** [comment]
You can close this one, the problem was in my code...
