### ISSUE TITLE
Isolate runtime dependendenies

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider-nrepl#143]
We have to find some way to isolate cider-nrepl's runtime deps from the runtime deps of projects using `cider-nrepl`. Currently we're cautious when introducing new deps to avoid conflicts, but this is limiting the functionality we can potentially implement in terms of middleware (as depending on a widely used 3rd party lib is a recipe for conflicts).

See the related discussion [here](https://github.com/clojure-emacs/refactor-nrepl/issues/20).

**Comment by benedekfazekas** [comment]
@bbatsov is there a list of candidate deps you want to introduce? I know mranderson is hm... suboptimal... or scary... or both... ;) but for certain libraries (basically without their own java classes) it does the trick.

**Comment by bbatsov** [comment]
> @bbatsov is there a list of candidate deps you want to introduce? I know mranderson is hm... suboptimal... or scary... or both... ;) but for certain libraries (basically without their own java classes) it does the trick.

Only in my mind. :-) And for some of them `mranderson` will do the trick, but frankly speaking - I don't want to deal with all the hassle it introduces and I'll still be faced with the Java deps issue. I'd like to find an universal approach (preferably one that doesn't involve manipulating the original artifacts).

**Comment by benedekfazekas** [comment]
fair enough

**Comment by bbatsov** [comment]
@benedekfazekas Seems we're out of ideas. Let's try using `mranderson` in cider-nrepl. Can you set this up?

**Comment by benedekfazekas** [comment]
i've already started playing with it yesterday evening. I hit a couple of bugs in mranderson so currently can't inline debugger, cljfmt and had to downgrade tools.reader to 0.8.12. with these modifications tests pass.

so to cut it short: working on it ;) will most likely push a branch when those fixes are done

**Comment by bbatsov** [comment]
> i've already started playing with it yesterday evening. I hit a couple of bugs in mranderson so currently can't inline debugger, cljfmt and had to downgrade tools.reader to 0.8.12. with these modifications tests pass.

What's special about them?

> so to cut it short: working on it ;) will most likely push a branch when those fixes are done

Nice!

**Comment by benedekfazekas** [comment]
> What's special about them?

nothing really. only they trigger certain bugs in mranderson (/me hangs head, goes away fixing his own bugs)

**Comment by benedekfazekas** [comment]
I've made some progress with this, tweaking mranderson. Strangely I am only stuck on the tools.reader problem. If I upgrade it to anything above 0.8.12 I get an exception when I run
    
    lein with-profile +plugin.mranderson/config test

(this is after all the inlining, clj munging is done). To make it even stranger I can upgrade tools.reader in refactor-nrepl to 0.8.13 or in fact 0.8.16 and mranderson it without problems.

it seems that somehow ExceptionInfo does not want to be AOT-ed:
```
Exception in thread "main" java.lang.ClassNotFoundException: deps.toolsreader.v0v8v13.clojure.tools.reader.impl.ExceptionInfo, compiling:(deps/toolsreader/v0v8v13/clojure/tools/reader/impl/ExceptionInfo.clj:23:1)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6567)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6548)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.access$100(Compiler.java:37)
	at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:529)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6560)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyze(Compiler.java:6322)
	at clojure.lang.Compiler.eval(Compiler.java:6623)
	at clojure.lang.Compiler.load(Compiler.java:7064)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.loadResourceScript(RT.java:361)
	at clojure.lang.RT.load(RT.java:440)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__8974.invoke(core.clj:5533)
	at clojure.core$load.doInvoke(core.clj:5532)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5339)
	at clojure.core$load_lib$fn__8923.invoke(core.clj:5378)
	at clojure.core$load_lib.doInvoke(core.clj:5377)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:619)
	at clojure.core$load_libs.doInvoke(core.clj:5416)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:619)
	at clojure.core$require.doInvoke(core.clj:5499)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at deps.toolsreader.v0v8v13.clojure.tools.reader.impl.utils$eval13209$loading__8850__auto____13210.invoke(utils.clj:9)
	at deps.toolsreader.v0v8v13.clojure.tools.reader.impl.utils$eval13209.invoke(utils.clj:9)
	at clojure.lang.Compiler.eval(Compiler.java:6619)
	at clojure.lang.Compiler.eval(Compiler.java:6608)
	at clojure.lang.Compiler.load(Compiler.java:7064)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.loadResourceScript(RT.java:361)
	at clojure.lang.RT.load(RT.java:440)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__8974.invoke(core.clj:5533)
	at clojure.core$load.doInvoke(core.clj:5532)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5339)
	at clojure.core$load_lib$fn__8923.invoke(core.clj:5378)
	at clojure.core$load_lib.doInvoke(core.clj:5377)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:619)
	at clojure.core$load_libs.doInvoke(core.clj:5416)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:621)
	at clojure.core$use.doInvoke(core.clj:5510)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at deps.toolsreader.v0v8v13.clojure.tools.reader.reader_types$eval13203$loading__8850__auto____13204.invoke(reader_types.clj:9)
	at deps.toolsreader.v0v8v13.clojure.tools.reader.reader_types$eval13203.invoke(reader_types.clj:9)
	at clojure.lang.Compiler.eval(Compiler.java:6619)
	at clojure.lang.Compiler.eval(Compiler.java:6608)
	at clojure.lang.Compiler.load(Compiler.java:7064)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.loadResourceScript(RT.java:361)
	at clojure.lang.RT.load(RT.java:440)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__8974.invoke(core.clj:5533)
	at clojure.core$load.doInvoke(core.clj:5532)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5339)
	at clojure.core$load_lib$fn__8923.invoke(core.clj:5378)
	at clojure.core$load_lib.doInvoke(core.clj:5377)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:619)
	at clojure.core$load_libs.doInvoke(core.clj:5416)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:621)
	at clojure.core$use.doInvoke(core.clj:5510)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at deps.toolsreader.v0v8v13.clojure.tools.reader.edn$eval13197$loading__8850__auto____13198.invoke(edn.clj:9)
	at deps.toolsreader.v0v8v13.clojure.tools.reader.edn$eval13197.invoke(edn.clj:9)
	at clojure.lang.Compiler.eval(Compiler.java:6619)
	at clojure.lang.Compiler.eval(Compiler.java:6608)
	at clojure.lang.Compiler.load(Compiler.java:7064)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.loadResourceScript(RT.java:361)
	at clojure.lang.RT.load(RT.java:440)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__8974.invoke(core.clj:5533)
	at clojure.core$load.doInvoke(core.clj:5532)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5339)
	at clojure.core$load_lib$fn__8923.invoke(core.clj:5378)
	at clojure.core$load_lib.doInvoke(core.clj:5377)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:619)
	at clojure.core$load_libs.doInvoke(core.clj:5416)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:619)
	at clojure.core$require.doInvoke(core.clj:5499)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at deps.cljfmt.v0v1v10.deps.rewrite_clj.v0v4v12.rewrite_clj.node.string$eval13191$loading__8850__auto____13192.invoke(string.clj:1)
	at deps.cljfmt.v0v1v10.deps.rewrite_clj.v0v4v12.rewrite_clj.node.string$eval13191.invoke(string.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6619)
	at clojure.lang.Compiler.eval(Compiler.java:6608)
	at clojure.lang.Compiler.load(Compiler.java:7064)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.loadResourceScript(RT.java:361)
```

my only guess is that somehow `cljfmt` interferes with tools.reader (rewrite-clj depends on tool.reader 0.8.13 and cljfmt depends on rewrite-clj)

I keep investigating.

**Comment by benedekfazekas** [comment]
strangely removing
```clojure
(def VERSION-FORM `(do (require 'cider-nrepl.plugin)
                       (alter-var-root #'cider-nrepl.plugin/version
                                       (constantly (constantly ~VERSION)))))
```
and the injection in dev mode referencing this VERSION-FORM solves the problem.
