### ISSUE TITLE
Pprint middleware has bad descriptor

### ISSUE THREAD

**Issue by Deraen** [clojure-emacs/cider-nrepl#207]
Describe op is failing when verbose info is asked. Fireplace is doing this when opening connection so this effectively breaks cider-nrepl with Fireplace.

Looks like the problem is with pprint descriptor: https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/pprint.clj#L61
As I understand the [tools.nrepl](https://github.com/clojure/tools.nrepl#middleware-descriptors-and-nrepl-server-configuration) documentation the `:requires` value should be map from slot to docstring instead of set containing a var? And `:expects` in line 62 doesn't make sense either, I think.

Adding a test calling describe op would probably be a good idea.

Stack trace:
```
user=> ERROR 2015-05-13 11:08:18.293 clojure.tools.nrepl.server: Unhandled REPL handler exception processing message {:id fireplace-juho-laptop-1431503213-18, :session 12243fd7-7658-4de8-98f8-b4ca6c20f188, :op describe, :verbose? 1}
java.lang.IllegalArgumentException: Cannot write value of type class clojure.lang.Var
	at clojure.tools.nrepl.bencode$eval926$fn__927.invoke(bencode.clj:326) ~[na:na]
	at clojure.lang.MultiFn.invoke(MultiFn.java:233) ~[clojure-1.7.0-beta2.jar:na]
	at clojure.tools.nrepl.bencode$eval951$fn__952.invoke(bencode.clj:382) ~[na:na]
	at clojure.lang.MultiFn.invoke(MultiFn.java:233) ~[clojure-1.7.0-beta2.jar:na]
	at clojure.tools.nrepl.bencode$eval961$fn__962.invoke(bencode.clj:398) ~[na:na]
	at clojure.lang.MultiFn.invoke(MultiFn.java:233) ~[clojure-1.7.0-beta2.jar:na]
	at clojure.tools.nrepl.bencode$eval961$fn__962.invoke(bencode.clj:398) ~[na:na]
	at clojure.lang.MultiFn.invoke(MultiFn.java:233) ~[clojure-1.7.0-beta2.jar:na]
	at clojure.tools.nrepl.bencode$eval961$fn__962.invoke(bencode.clj:398) ~[na:na]
	at clojure.lang.MultiFn.invoke(MultiFn.java:233) ~[clojure-1.7.0-beta2.jar:na]
	at clojure.tools.nrepl.transport$bencode$fn__1397.invoke(transport.clj:103) ~[na:na]
	at clojure.tools.nrepl.transport.FnTransport.send(transport.clj:28) ~[na:na]
	at clojure.tools.nrepl.middleware.render_values$wrap_renderer$reify__2282.send(render_values.clj:33) ~[na:na]
	at clojure.tools.nrepl.middleware$wrap_describe$fn__1584.invoke(middleware.clj:55) ~[na:na]
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1568.invoke(middleware.clj:22) ~[na:na]
	at cider.nrepl.middleware.stacktrace$wrap_stacktrace$fn__7761.invoke(stacktrace.clj:164) ~[na:na]
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1568.invoke(middleware.clj:22) ~[na:na]
	at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__1819.invoke(interruptible_eval.clj:216) ~[na:na]
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1568.invoke(middleware.clj:22) ~[na:na]
	at cider.nrepl.middleware.undef$wrap_undef$fn__8207.invoke(undef.clj:30) ~[na:na]
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1568.invoke(middleware.clj:22) ~[na:na]
	at cider.nrepl.middleware.debug$wrap_debug$fn__4479.invoke(debug.clj:206) ~[na:na]
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1568.invoke(middleware.clj:22) ~[na:na]
	at clojure.tools.nrepl.middleware.session$add_stdin$fn__1898.invoke(session.clj:238) ~[na:na]
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1568.invoke(middleware.clj:22) ~[na:na]
	at cider.nrepl.middleware.macroexpand$wrap_macroexpand$fn__7538.invoke(macroexpand.clj:84) ~[na:na]
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1568.invoke(middleware.clj:22) ~[na:na]
	at cider.nrepl.middleware.inspect$wrap_inspect$fn__7498.invoke(inspect.clj:81) ~[na:na]
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1568.invoke(middleware.clj:22) ~[na:na]
	at cider.nrepl.middleware.resource$wrap_resource$fn__7821.invoke(resource.clj:49) ~[na:na]
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1568.invoke(middleware.clj:22) ~[na:na]
	at user$eval10832$fn__10833$fn__10835.invoke(form-init7065463279626069410.clj:1) ~[na:na]
	at cider.nrepl.middleware.info$wrap_info$fn__4237.invoke(info.clj:265) ~[na:na]
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1568.invoke(middleware.clj:22) ~[na:na]
	at cider.nrepl.middleware.apropos$wrap_apropos$fn__2406.invoke(apropos.clj:102) ~[na:na]
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1568.invoke(middleware.clj:22) ~[na:na]
	at clojure.tools.nrepl.middleware.load_file$wrap_load_file$fn__1939.invoke(load_file.clj:79) ~[na:na]
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1568.invoke(middleware.clj:22) ~[na:na]
	at cider.nrepl.middleware.refresh$wrap_refresh$fn__7791.invoke(refresh.clj:54) ~[na:na]
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1568.invoke(middleware.clj:22) ~[na:na]
	at cider.nrepl.middleware.classpath$wrap_classpath$fn__2500.invoke(classpath.clj:25) ~[na:na]
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1568.invoke(middleware.clj:22) ~[na:na]
	at cider.nrepl.middleware.complete$wrap_complete$fn__3759.invoke(complete.clj:52) ~[na:na]
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1568.invoke(middleware.clj:22) ~[na:na]
	at cider.nrepl.middleware.pprint$wrap_pprint$fn__7677.invoke(pprint.clj:51) ~[na:na]
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1568.invoke(middleware.clj:22) ~[na:na]
	at clojure.tools.nrepl.middleware.render_values$render_values$fn__2288.invoke(render_values.clj:45) ~[na:na]
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1568.invoke(middleware.clj:22) ~[na:na]
	at cider.nrepl.middleware.format$wrap_format$fn__7309.invoke(format.clj:58) ~[na:na]
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1568.invoke(middleware.clj:22) ~[na:na]
	at cider.nrepl.middleware.test$wrap_test$fn__7912.invoke(test.clj:203) ~[na:na]
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1568.invoke(middleware.clj:22) ~[na:na]
	at clojure.tools.nrepl.middleware.session$session$fn__1883.invoke(session.clj:192) ~[na:na]
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1568.invoke(middleware.clj:22) ~[na:na]
	at cider.nrepl.middleware.trace$wrap_trace$fn__8179.invoke(trace.clj:65) ~[na:na]
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1568.invoke(middleware.clj:22) ~[na:na]
	at cider.nrepl.middleware.ns$wrap_ns$fn__7643.invoke(ns.clj:105) ~[na:na]
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1568.invoke(middleware.clj:22) ~[na:na]
	at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:19) ~[na:na]
	at clojure.tools.nrepl.server$handle$fn__1954.invoke(server.clj:28) [na:na]
	at clojure.core$binding_conveyor_fn$fn__4441.invoke(core.clj:1914) [clojure-1.7.0-beta2.jar:na]
	at clojure.lang.AFn.call(AFn.java:18) [clojure-1.7.0-beta2.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

**Comment by cichli** [comment]
Good spot - both of those look entirely superfluous to me. I'm not sure how the describe op is succeeding for CIDER though. I'll sort this out today.

**Comment by Deraen** [comment]
Perhaps CIDER doesn't use `:verbose? 1`.

**Comment by cichli** [comment]
> Perhaps CIDER doesn't use :verbose? 1.

Yep, that was it.

> Adding a test calling describe op would probably be a good idea.

Done.

Thanks for the report!
