### ISSUE TITLE
Illegal hex characters in escape (%) pattern - For input string: "s/"

### ISSUE THREAD

**Issue by zshamrock** [clojure-emacs/cider-nrepl#243]
```
ERROR: Unhandled REPL handler exception processing message {:id fireplace-debian-1439128204-4, :session 835584ef-88c0-4926-9446-a2d1bcb30326, :op cl$
sspath}
java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: "s/"
        at java.net.URLDecoder.decode(URLDecoder.java:194)
        **at cider.nrepl.middleware.classpath$classpath$fn__1336.invoke(classpath.clj:9)**
        at clojure.core$map$fn__4245.invoke(core.clj:2559)
...
```

When running `:Connect` from vim fireplace. 
CLASSPATH is 
```
$ echo $CLASSPATH 
/home/alex/tools/aspectj/aspectj-1.7/lib/aspectjrt.jar:/home/alex/tools/clojure/clojure-1.7.0/clojure-1.7.0.jar:.
```
Using cider 0.9.1:
```
$ cat .lein/profiles.clj 
{:system 
 {:dependencies [[org.clojure/clojure "1.7.0"]]}
 :user {:plugins [[lein-midje "3.1.3"]
                  [cider/cider-nrepl "0.9.1"]
                  [lein-oneoff "0.3.1"]]}
 }
```

and Oracle JDK 1.8.0_25

**Comment by cichli** [comment]
Thanks for the report - I've deployed `cider-nrepl 0.10.0-SNAPSHOT`, will you try it out and see if you still get the error?

**Comment by zshamrock** [comment]
Yes, thank you @cichli, I've tried the SNAPSHOT, and it works.

**Comment by gpwclark** [comment]
@cichli thanks for the snapshot.
