### ISSUE TITLE
Failed to start nrepl server in cider-nrepl 20151217

### ISSUE THREAD

**Issue by sunng87** [clojure-emacs/cider-nrepl#276]
I'm getting a few errors:

```
Error loading cider.nrepl.middleware.debug: java.io.FileNotFoundException: Could not locate cider/inlined_deps/fipp/v0v6v3/fipp/edn__init.class or cider/inlined_deps/fipp/v0v6v3/fipp/edn.clj on classpath: , compiling:(cider/nrepl/middleware/pprint.clj:1:1)
Error loading cider.nrepl.middleware.format: java.io.FileNotFoundException: Could not locate cider/inlined_deps/fipp/v0v6v3/fipp/edn__init.class or cider/inlined_deps/fipp/v0v6v3/fipp/edn.clj on classpath: , compiling:(cider/nrepl/middleware/pprint.clj:1:1)
Error loading cider.nrepl.middleware.pprint: java.io.FileNotFoundException: Could not locate cider/inlined_deps/fipp/v0v6v3/fipp/edn__init.class or cider/inlined_deps/fipp/v0v6v3/fipp/edn.clj on classpath: , compiling:(cider/nrepl/middleware/pprint.clj:1:1)
Error loading cider.nrepl.middleware.pprint: java.io.FileNotFoundException: Could not locate cider/inlined_deps/fipp/v0v6v3/fipp/edn__init.class or cider/inlined_deps/fipp/v0v6v3/fipp/edn.clj on classpath: , compiling:(cider/nrepl/middleware/pprint.clj:1:1)
Error loading cider.nrepl.middleware.refresh: java.io.FileNotFoundException: Could not locate cider/inlined_deps/fipp/v0v6v3/fipp/edn__init.class or cider/inlined_deps/fipp/v0v6v3/fipp/edn.clj on classpath: , compiling:(cider/nrepl/middleware/pprint.clj:1:1)
Error loading cider.nrepl.middleware.stacktrace: java.io.FileNotFoundException: Could not locate cider/inlined_deps/fipp/v0v6v3/fipp/edn__init.class or cider/inlined_deps/fipp/v0v6v3/fipp/edn.clj on classpath: , compiling:(cider/nrepl/middleware/pprint.clj:1:1)
Error loading cider.nrepl.middleware.test: java.io.FileNotFoundException: Could not locate cider/inlined_deps/fipp/v0v6v3/fipp/edn__init.class or cider/inlined_deps/fipp/v0v6v3/fipp/edn.clj on classpath: , compiling:(cider/nrepl/middleware/pprint.clj:1:1)
Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: cider.nrepl.middleware.debug/wrap-debug in this context, compiling:(/tmp/form-init3484554218543925332.clj:1:8172)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6651)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3719)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6646)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3719)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6646)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.access$100(Compiler.java:38)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6050)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5782)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5217)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3846)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6642)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.eval(Compiler.java:6700)
	at clojure.lang.Compiler.eval(Compiler.java:6693)
	at clojure.lang.Compiler.eval(Compiler.java:6693)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Unable to resolve var: cider.nrepl.middleware.debug/wrap-debug in this context
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler$TheVarExpr$Parser.parse(Compiler.java:659)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644)
	... 34 more
```

Is this an known issue?

**Comment by bbatsov** [comment]
Update your Leiningen to 2.5.3.

**Comment by sunng87** [comment]
I'm on 2.5.3

```
 $ lein version  
Leiningen 2.5.3 on Java 1.8.0_66 OpenJDK 64-Bit Server VM
```

**Comment by bbatsov** [comment]
Clojure version?

**Comment by sunng87** [comment]
My project is on Clojure 1.6

**Comment by cichli** [comment]
0.10.0 is the last version of CIDER to support Clojure versions before 1.7. You'll have to either upgrade your Clojure version, or downgrade CIDER.
