### ISSUE TITLE
How to use cider with [org.clojure/clojure "1.9.0-alpha20"] ?

### ISSUE THREAD

**Issue by mattiasw2** [clojure-emacs/cider-nrepl#441]
cider-nrepl 0.15.0

## Actual behavior
```

java.lang.ExceptionInInitializerError
	at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.RuntimeException: Invalid token: ::clojure.test/once-fixtures, compiling:(cider/nrepl/middleware/test.clj:129:57)
	at clojure.lang.Compiler.load(Compiler.java:7521)
```

## Steps to reproduce the problem

This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.

### cider-nrepl version

0.15.0

### Java version

1.8.0_131

### Operating system

Windows 10

**Comment by mattiasw2** [comment]
Solved: use 0.15.1-SNAPSHOT
