### ISSUE TITLE
Can't run regular deftests anymore

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider-nrepl#529]
`CIDER 0.17.0snapshot (package: 20180506.1409)`

I haven't updated CIDER in a while, but I did so just now to see if it fixed this.  I think another cider-nrepl snapshot was pulled in which caused some breakage.

All my regular

```
(deftest a-test 
  (is (= 1 1)))
```
tests stopped working today.  They all fail with 'No assertions (or no tests) were run.Did you forget to use ‘is’ in your tests?`

I see there's been some recent test-related refactoring today.  I hope https://github.com/clojure-emacs/cider-nrepl/pull/528 is the solution.  

If this is broken for me, on this 100% vanilla setup, it's broken for everyone else.

**Comment by SevereOverfl0w** [comment]
#528 is the solution fix for this, yep.

**Comment by SevereOverfl0w** [comment]
This should be fixed on the latest snapshot, can you give it a spin?

**Comment by expez** [comment]
@SevereOverfl0w I get this in the REPL, instead of a successful test run:

```
java.lang.IllegalArgumentException: Symbol must be namespace-qualified
	at clojure.lang.Var.find(Var.java:138)
	at clojure.core$find_var.invokeStatic(core.clj:2010)
	at clojure.core$find_var.invoke(core.clj:2005)
	at clojure.core$comp$fn__6817.invoke(core.clj:2542)
	at clojure.core$keep$fn__9474.invoke(core.clj:7210)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:525)
	at clojure.core$seq__6416.invokeStatic(core.clj:137)
	at clojure.core$seq__6416.invoke(core.clj:137)
	at cider.nrepl.middleware.util.coerce$var_query$fn__38891.invoke(coerce.clj:37)
	at clojure.core$update.invokeStatic(core.clj:6078)
	at clojure.core$update.invoke(core.clj:6070)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:661)
	at clojure.core$apply.invoke(core.clj:652)
	at cider.nrepl.middleware.util.coerce$update_some.invokeStatic(coerce.clj:7)
	at cider.nrepl.middleware.util.coerce$update_some.doInvoke(coerce.clj:4)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at cider.nrepl.middleware.util.coerce$var_query.invokeStatic(coerce.clj:37)
	at cider.nrepl.middleware.util.coerce$var_query.invoke(coerce.clj:33)
	at cider.nrepl.middleware.test$handle_test_var_query_op$fn__39060$fn__39061$fn__39062.invoke(test.clj:284)
	at cider.nrepl.middleware.test$handle_test_var_query_op$fn__39060$fn__39061.invoke(test.clj:279)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1963)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1963)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at cider.nrepl.middleware.test$handle_test_var_query_op$fn__39060.invoke(test.clj:277)
	at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__22130.invoke(interruptible_eval.clj:190)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by expez** [comment]
If anyone else runs into this, prior to 17.1 getting released, you can either downgrade or change your test name temporarily from `bar` to `foo/bar`

**Comment by SevereOverfl0w** [comment]
I tested this on spacemacs after a `cider-connect`.

I did a `cider-refresh` followed by `cider-run-focused-test` and it ran the test under my cursor.

I can't understand how this exception could be thrown unless the old version of cider-nrepl is in play.

**Comment by expez** [comment]
@SevereOverfl0w <kbd> C-c C-t C-t</kbd> runs ` cider-test-run-test`, which runs the test surround the cursor.

I can't find any references to the function `cider-run-focused-test` in the CIDER codebase, perhaps this is something that only exists locally in your .emacs?
