### ISSUE TITLE
cannot connect to nrepl server via cider connect cljs 

### ISSUE THREAD

**Issue by drewverlee** [clojure-emacs/cider-nrepl#541]
Use the template below when reporting bugs. Please, make sure that
you're running the latest stable release or the latest snapshot of
`cider-nrepl` and that the problem you're reporting hasn't been
reported (and potentially fixed) already.

## Expected behavior

able to connect to nrepl server via lein figwheel android

## Actual behavior

not able to connect, connection closed with error

## Steps to reproduce the problem

lein figwheel android 
cider-connect-cljs via emacs

project.clj
fighweel-sidecar: 0.5.15
cider/piggieback 0.3.18
org.clojure/tools.nrelp 0.2.13
```
setup in project clj
:figwheel {:nrepl-port 7888
  ;; Load CIDER, refactor-nrepl and piggieback middleware
             :nrepl-middleware ["cider.nrepl/cider-middleware"
                                "refactor-nrepl.middleware/wrap-refactor"
                                "cider.piggieback/wrap-cljs-repl"]}
````
profiles > dev > dependeices > repl-options 
```
  {:nrepl-middleware [cider.piggieback/wrap-cljs-repl]}}
```

##error output 

➜  ✗ lein figwheel android
Figwheel: Cutting some fruit, just a sec ...
re-frisk server has been started at http://localhost:4567
Figwheel: Validating the configuration found in project.clj
Figwheel: Configuration Valid ;)
Figwheel: Starting server at http://0.0.0.0:3449
Figwheel: Watching build - android
Compiling build :android to "target/android/index.js" from ("src/" "lib/common/src/" "lib/client-api/src/" "env/dev/")...
Successfully compiled build :android to "target/android/index.js" in 2.863 seconds.
Figwheel: Starting nREPL server on port: 7888
[WARNING] No nREPL middleware descriptor in metadata of #'cider.piggieback/wrap-cljs-repl, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.piggieback/wrap-cljs-repl, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.piggieback/wrap-cljs-repl, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.piggieback/wrap-cljs-repl, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.piggieback/wrap-cljs-repl, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.piggieback/wrap-cljs-repl, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.piggieback/wrap-cljs-repl, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.piggieback/wrap-cljs-repl, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.piggieback/wrap-cljs-repl, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.piggieback/wrap-cljs-repl, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.piggieback/wrap-cljs-repl, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-apropos, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-classpath, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-complete, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-debug, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-enlighten, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-format, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-info, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-inspect, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-macroexpand, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-slurp, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-ns, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-out, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-content-type, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-slurp, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-pprint, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-pprint-fn, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-profile, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-refresh, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-resource, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-spec, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-stacktrace, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-test, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-trace, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-tracker, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-undef, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-version, see clojure.tools.middleware/set-descriptor!
Launching ClojureScript REPL for build: android
Figwheel Controls:
          (stop-autobuild)                ;; stops Figwheel autobuilder
          (start-autobuild id ...)        ;; starts autobuilder focused on optional ids
          (switch-to-build id ...)        ;; switches autobuilder to different build
          (reset-autobuild)               ;; stops, cleans, and starts autobuilder
          (reload-config)                 ;; reloads build config and resets autobuild
          (build-once id ...)             ;; builds source one time
          (clean-builds id ..)            ;; deletes compiled cljs target files
          (print-config id ...)           ;; prints out build configurations
          (fig-status)                    ;; displays current state of system
          (figwheel.client/set-autoload false)    ;; will turn autoloading off
          (figwheel.client/set-repl-pprint false) ;; will turn pretty printing off
  Switch REPL build focus:
          :cljs/quit                      ;; allows you to switch REPL to another build
    Docs: (doc function-name-here)
    Exit: :cljs/quit
 Results: Stored in vars *1, *2, *3, *e holds last exception object
Prompt will show when Figwheel connects to your application
[Rebel readline] Type :repl/help for online help info
Jul 31, 2018 11:38:49 AM clojure.tools.nrepl.server invoke
SEVERE: Unhandled REPL handler exception processing message {:op init-debugger, :print-level 10, :print-length 10, :session 450c1945-334c-434a-bd95-bad336f9521b, :id 8}
java.lang.IllegalAccessError: whitespace? does not exist, compiling:(cider/inlined_deps/toolsreader/v1v1v3v1/clojure/tools/reader/reader_types.clj:1:1)
	at clojure.lang.Compiler.load(Compiler.java:7526)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:482)
	at cider.inlined_deps.toolsreader.v1v1v3v1.clojure.tools.reader$eval43637$loading__6434__auto____43638.invoke(reader.clj:9)
	at cider.inlined_deps.toolsreader.v1v1v3v1.clojure.tools.reader$eval43637.invokeStatic(reader.clj:9)
	at cider.inlined_deps.toolsreader.v1v1v3v1.clojure.tools.reader$eval43637.invoke(reader.clj:9)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at cider.inlined_deps.toolsnamespace.v0v3v0_alpha4.clojure.tools.namespace.parse$eval43625$loading__6434__auto____43627.invoke(parse.cljc:9)
	at cider.inlined_deps.toolsnamespace.v0v3v0_alpha4.clojure.tools.namespace.parse$eval43625.invokeStatic(parse.cljc:9)
	at cider.inlined_deps.toolsnamespace.v0v3v0_alpha4.clojure.tools.namespace.parse$eval43625.invoke(parse.cljc:9)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at cider.inlined_deps.toolsnamespace.v0v3v0_alpha4.clojure.tools.namespace.file$eval43611$loading__6434__auto____43612.invoke(file.clj:9)
	at cider.inlined_deps.toolsnamespace.v0v3v0_alpha4.clojure.tools.namespace.file$eval43611.invokeStatic(file.clj:9)
	at cider.inlined_deps.toolsnamespace.v0v3v0_alpha4.clojure.tools.namespace.file$eval43611.invoke(file.clj:9)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:551)
	at cider.inlined_deps.orchard.v0v3v0.orchard.namespace$eval43599$loading__6434__auto____43600.invoke(namespace.clj:1)
	at cider.inlined_deps.orchard.v0v3v0.orchard.namespace$eval43599.invokeStatic(namespace.clj:1)
	at cider.inlined_deps.orchard.v0v3v0.orchard.namespace$eval43599.invoke(namespace.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:619)
	at cider.inlined_deps.orchard.v0v3v0.orchard.meta$eval43587$loading__6434__auto____43588.invoke(meta.clj:1)
	at cider.inlined_deps.orchard.v0v3v0.orchard.meta$eval43587.invokeStatic(meta.clj:1)
	at cider.inlined_deps.orchard.v0v3v0.orchard.meta$eval43587.invoke(meta.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:703)
	at cider.inlined_deps.orchard.v0v3v0.orchard.info$eval43571$loading__6434__auto____43572.invoke(info.clj:1)
	at cider.inlined_deps.orchard.v0v3v0.orchard.info$eval43571.invokeStatic(info.clj:1)
	at cider.inlined_deps.orchard.v0v3v0.orchard.info$eval43571.invoke(info.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at cider.nrepl.middleware.debug$eval43560$loading__6434__auto____43562.invoke(debug.clj:1)
	at cider.nrepl.middleware.debug$eval43560.invokeStatic(debug.clj:1)
	at cider.nrepl.middleware.debug$eval43560.invoke(debug.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at cider.nrepl$run_deferred_handler$fn__32150.invoke(nrepl.clj:37)
	at clojure.lang.Delay.deref(Delay.java:42)
	at clojure.core$deref.invokeStatic(core.clj:2312)
	at clojure.core$deref.invoke(core.clj:2298)
	at cider.nrepl$wrap_debug$fn__32240.invoke(nrepl.clj:181)
	at nrepl.middleware$wrap_conj_descriptor$fn__31267.invoke(middleware.clj:22)
	at clojure.tools.nrepl.server$handle_STAR_.invokeStatic(server.clj:19)
	at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:16)
	at clojure.tools.nrepl.server$handle$fn__29032.invoke(server.clj:28)
	at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2022)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalAccessError: whitespace? does not exist
	at clojure.core$refer.invokeStatic(core.clj:4215)
	at clojure.core$refer.doInvoke(core.clj:4183)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_lib.invokeStatic(core.clj:5906)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at cider.inlined_deps.toolsreader.v1v1v3v1.clojure.tools.reader.reader_types$eval43652$loading__6434__auto____43655.invoke(reader_types.clj:9)
	at cider.inlined_deps.toolsreader.v1v1v3v1.clojure.tools.reader.reader_types$eval43652.invokeStatic(reader_types.clj:9)
	at cider.inlined_deps.toolsreader.v1v1v3v1.clojure.tools.reader.reader_types$eval43652.invoke(reader_types.clj:9)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	... 233 more

Jul 31, 2018 11:38:50 AM clojure.tools.nrepl.server invoke
SEVERE: Unhandled REPL handler exception processing message {:op classpath, :session 450c1945-334c-434a-bd95-bad336f9521b, :id 9}
java.lang.IllegalArgumentException: No implementation of method: :send of protocol: #'nrepl.transport/Transport found for class: clojure.tools.nrepl.transport.FnTransport
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
	at nrepl.transport$eval31023$fn__31024$G__31014__31031.invoke(transport.clj:13)
	at cider.nrepl.middleware.classpath$handle_classpath.invokeStatic(classpath.clj:9)
	at cider.nrepl.middleware.classpath$handle_classpath.invoke(classpath.clj:8)
	at clojure.lang.Var.invoke(Var.java:385)
	at cider.nrepl$wrap_classpath$fn__32222.invoke(nrepl.clj:155)
	at nrepl.middleware$wrap_conj_descriptor$fn__31267.invoke(middleware.clj:22)
	at cider.nrepl$wrap_version$fn__32378.invoke(nrepl.clj:492)
	at nrepl.middleware$wrap_conj_descriptor$fn__31267.invoke(middleware.clj:22)
	at cider.nrepl$wrap_format$fn__32256.invoke(nrepl.clj:211)
	at nrepl.middleware$wrap_conj_descriptor$fn__31267.invoke(middleware.clj:22)
	at cider.nrepl$wrap_tracker$fn__32362.invoke(nrepl.clj:473)
	at nrepl.middleware$wrap_conj_descriptor$fn__31267.invoke(middleware.clj:22)
	at cider.nrepl$wrap_enlighten$fn__32248.invoke(nrepl.clj:207)
	at nrepl.middleware$wrap_conj_descriptor$fn__31267.invoke(middleware.clj:22)
	at cider.nrepl$wrap_inspect$fn__32274.invoke(nrepl.clj:244)
	at nrepl.middleware$wrap_conj_descriptor$fn__31267.invoke(middleware.clj:22)
	at cider.nrepl$wrap_out$fn__32298.invoke(nrepl.clj:325)
	at nrepl.middleware$wrap_conj_descriptor$fn__31267.invoke(middleware.clj:22)
	at cider.nrepl$wrap_complete$fn__32230.invoke(nrepl.clj:161)
	at nrepl.middleware$wrap_conj_descriptor$fn__31267.invoke(middleware.clj:22)
	at cider.nrepl$wrap_apropos$fn__32214.invoke(nrepl.clj:147)
	at nrepl.middleware$wrap_conj_descriptor$fn__31267.invoke(middleware.clj:22)
	at cider.nrepl$wrap_undef$fn__32370.invoke(nrepl.clj:484)
	at nrepl.middleware$wrap_conj_descriptor$fn__31267.invoke(middleware.clj:22)
	at cider.nrepl$wrap_trace$fn__32354.invoke(nrepl.clj:455)
	at nrepl.middleware$wrap_conj_descriptor$fn__31267.invoke(middleware.clj:22)
	at cider.nrepl$wrap_profile$fn__32306.invoke(nrepl.clj:334)
	at nrepl.middleware$wrap_conj_descriptor$fn__31267.invoke(middleware.clj:22)
	at cider.nrepl$wrap_refresh$fn__32314.invoke(nrepl.clj:371)
	at nrepl.middleware$wrap_conj_descriptor$fn__31267.invoke(middleware.clj:22)
	at cider.nrepl$wrap_debug$fn__32240.invoke(nrepl.clj:181)
	at nrepl.middleware$wrap_conj_descriptor$fn__31267.invoke(middleware.clj:22)
	at clojure.tools.nrepl.server$handle_STAR_.invokeStatic(server.clj:19)
	at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:16)
	at clojure.tools.nrepl.server$handle$fn__29032.invoke(server.clj:28)
	at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2022)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Jul 31, 2018 11:38:50 AM clojure.tools.nrepl.server invoke
SEVERE: Unhandled REPL handler exception processing message {:op out-subscribe, :session 450c1945-334c-434a-bd95-bad336f9521b, :id 7}
java.lang.IllegalArgumentException: No implementation of method: :send of protocol: #'nrepl.transport/Transport found for class: clojure.tools.nrepl.transport.FnTransport
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
	at nrepl.transport$eval31023$fn__31024$G__31014__31031.invoke(transport.clj:13)
	at cider.nrepl.middleware.out$handle_out.invokeStatic(out.clj:122)
	at cider.nrepl.middleware.out$handle_out.invoke(out.clj:121)
	at clojure.lang.Var.invoke(Var.java:385)
	at cider.nrepl$wrap_out$fn__32298.invoke(nrepl.clj:325)
	at nrepl.middleware$wrap_conj_descriptor$fn__31267.invoke(middleware.clj:22)
	at cider.nrepl$wrap_complete$fn__32230.invoke(nrepl.clj:161)
	at nrepl.middleware$wrap_conj_descriptor$fn__31267.invoke(middleware.clj:22)
	at cider.nrepl$wrap_apropos$fn__32214.invoke(nrepl.clj:147)
	at nrepl.middleware$wrap_conj_descriptor$fn__31267.invoke(middleware.clj:22)
	at cider.nrepl$wrap_undef$fn__32370.invoke(nrepl.clj:484)
	at nrepl.middleware$wrap_conj_descriptor$fn__31267.invoke(middleware.clj:22)
	at cider.nrepl$wrap_trace$fn__32354.invoke(nrepl.clj:455)
	at nrepl.middleware$wrap_conj_descriptor$fn__31267.invoke(middleware.clj:22)
	at cider.nrepl$wrap_profile$fn__32306.invoke(nrepl.clj:334)
	at nrepl.middleware$wrap_conj_descriptor$fn__31267.invoke(middleware.clj:22)
	at cider.nrepl$wrap_refresh$fn__32314.invoke(nrepl.clj:371)
	at nrepl.middleware$wrap_conj_descriptor$fn__31267.invoke(middleware.clj:22)
	at cider.nrepl$wrap_debug$fn__32240.invoke(nrepl.clj:181)
	at nrepl.middleware$wrap_conj_descriptor$fn__31267.invoke(middleware.clj:22)
	at clojure.tools.nrepl.server$handle_STAR_.invokeStatic(server.clj:19)
	at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:16)
	at clojure.tools.nrepl.server$handle$fn__29032.invoke(server.clj:28)
	at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2022)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.

### cider-nrepl version

E.g. 0.19.0-snapshot

### Java version

E.g. 1.8

### Operating system

E.g. ubuntu 18

**Comment by bbatsov** [comment]
Basically that's failing for you https://github.com/nrepl/piggieback/blob/master/src/cider/piggieback.clj#L19

I can't imagine why, though. I tested it with `lein repl` and it worked just fine. The idea is that if the old nREPL is loaded we use it, otherwise we leverage the new one.

**Comment by drewverlee** [comment]
i changed the cider-nrepl version back to 18 and things are working as expected. it seems i had a version mismatch. sorry about the confusion!

**Comment by bbatsov** [comment]
Ah, now I get it. You were on 0.19-SNAPSHOT which unconditionally requires nREPL 0.4. I was thinking that it would probably be best to employ the same approach I took with piggieback in CIDER 0.18 as well, as it will ensure a much smoother migration for most users.
