### ISSUE TITLE
complete causing 100% CPU emacs/JVM unresponsiveness

### ISSUE THREAD

**Issue by jappy** [clojure-emacs/cider-nrepl#588]
## Expected behavior

Whenever I type a keyword in Emacs I would like to just keep typing without Emacs or my JVM becoming unresponsive.

## Actual behavior

Whenever I type a keyword in Emacs while jacked in my JVM with millions of keyword using cider/cider-repl my CPU blows up to 100% for several minutes. Sometimes it goes back to normal, sometimes it doesn't.

## Steps to reproduce the problem

My JVM has millions of keywords. This issue only happens when you have lots of them (I have 14+ million of them). Then when you are jacked in from emacs and type a keyword the `handle-complete` function is called and all of the threads on my system are filled with calls through this function--thread dump example below.

My guess is that this code is not written with the possibility that there might be many millions of keywords in a system... and that it is trying to find all of the matches and sort them, etc. My best guess anyway. So to reproduce make a ton (like I said I have 14+ million) of pretty lengthy keywords and put them in the same namespace. Then jack into the JVM and then start typing one of the keywords in this namespace.

Here is a stack trace (many thread in the VM are doing the same):

```
"clojure-agent-send-off-pool-6" #27 prio=5 os_prio=31 cpu=26244.47ms elapsed=33.95s tid=0x00007f8ca13e6800 nid=0x14e03 runnable  [0x000070000e982000]
   java.lang.Thread.State: RUNNABLE
	at compliment.core$reify__15238.compare(core.clj:35)
	at clojure.core$sort_by$fn__5963.invoke(core.clj:3131)
	at clojure.lang.AFunction.compare(AFunction.java:51)
	at java.util.TimSort.binarySort(java.base@11.0.1/TimSort.java:296)
	at java.util.TimSort.sort(java.base@11.0.1/TimSort.java:239)
	at java.util.Arrays.sort(java.base@11.0.1/Arrays.java:1441)
	at clojure.core$sort.invokeStatic(core.clj:3115)
	at clojure.core$sort_by.invokeStatic(core.clj:3119)
	at clojure.core$sort_by.invoke(core.clj:3119)
	at compliment.core$completions.invokeStatic(core.clj:90)
	at compliment.core$completions.invoke(core.clj:54)
	at cider.nrepl.middleware.complete$complete.invokeStatic(complete.clj:20)
	at cider.nrepl.middleware.complete$complete.invoke(complete.clj:10)
	at cider.nrepl.middleware.complete$complete_reply.invokeStatic(complete.clj:30)
	at cider.nrepl.middleware.complete$complete_reply.invoke(complete.clj:29)
	at cider.nrepl.middleware.util.error_handling$eval11693$fn__11694.invoke(error_handling.clj:159)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at cider.nrepl.middleware.complete$handle_complete.invokeStatic(complete.clj:42)
	at cider.nrepl.middleware.complete$handle_complete.invoke(complete.clj:41)
	at clojure.lang.Var.invoke(Var.java:388)
	at cider.nrepl$wrap_complete$fn__1572.invoke(nrepl.clj:140)
	at nrepl.middleware$wrap_conj_descriptor$fn__803.invoke(middleware.clj:17)
	at cider.nrepl$wrap_trace$fn__1696.invoke(nrepl.clj:443)
	at nrepl.middleware$wrap_conj_descriptor$fn__803.invoke(middleware.clj:17)
	at cider.nrepl$wrap_apropos$fn__1556.invoke(nrepl.clj:126)
	at nrepl.middleware$wrap_conj_descriptor$fn__803.invoke(middleware.clj:17)
	at cider.nrepl$wrap_undef$fn__1712.invoke(nrepl.clj:472)
	at nrepl.middleware$wrap_conj_descriptor$fn__803.invoke(middleware.clj:17)
	at cider.nrepl$wrap_content_type$fn__1540.invoke(nrepl.clj:107)
	at nrepl.middleware$wrap_conj_descriptor$fn__803.invoke(middleware.clj:17)
	at cider.nrepl$wrap_info$fn__1606.invoke(nrepl.clj:205)
	at nrepl.middleware$wrap_conj_descriptor$fn__803.invoke(middleware.clj:17)
	at nrepl.middleware.session$add_stdin$fn__1249.invoke(session.clj:243)
	at nrepl.middleware$wrap_conj_descriptor$fn__803.invoke(middleware.clj:17)
	at cider.nrepl$wrap_version$fn__1720.invoke(nrepl.clj:480)
	at nrepl.middleware$wrap_conj_descriptor$fn__803.invoke(middleware.clj:17)
	at cider.nrepl$wrap_profile$fn__1648.invoke(nrepl.clj:322)
	at nrepl.middleware$wrap_conj_descriptor$fn__803.invoke(middleware.clj:17)
	at cider.nrepl$wrap_classpath$fn__1564.invoke(nrepl.clj:134)
	at nrepl.middleware$wrap_conj_descriptor$fn__803.invoke(middleware.clj:17)
	at cider.nrepl$wrap_format$fn__1598.invoke(nrepl.clj:190)
	at nrepl.middleware$wrap_conj_descriptor$fn__803.invoke(middleware.clj:17)
	at cider.nrepl$wrap_stacktrace$fn__1680.invoke(nrepl.clj:413)
	at nrepl.middleware$wrap_conj_descriptor$fn__803.invoke(middleware.clj:17)
	at nrepl.middleware.pr_values$pr_values$fn__1061.invoke(pr_values.clj:69)
	at nrepl.middleware$wrap_conj_descriptor$fn__803.invoke(middleware.clj:17)
	at cider.nrepl$wrap_test$fn__1688.invoke(nrepl.clj:423)
	at nrepl.middleware$wrap_conj_descriptor$fn__803.invoke(middleware.clj:17)
	at cider.nrepl$wrap_enlighten$fn__1590.invoke(nrepl.clj:186)
	at nrepl.middleware$wrap_conj_descriptor$fn__803.invoke(middleware.clj:17)
	at cider.nrepl$wrap_refresh$fn__1656.invoke(nrepl.clj:359)
	at nrepl.middleware$wrap_conj_descriptor$fn__803.invoke(middleware.clj:17)
	at cider.nrepl.middleware.pprint$handle_pprint_fn.invokeStatic(pprint.clj:29)
	at cider.nrepl.middleware.pprint$handle_pprint_fn.invoke(pprint.clj:24)
	at clojure.lang.Var.invoke(Var.java:388)
	at cider.nrepl$wrap_pprint_fn$fn__1530.invoke(nrepl.clj:87)
	at nrepl.middleware$wrap_conj_descriptor$fn__803.invoke(middleware.clj:17)
	at cider.nrepl$wrap_tracker$fn__1704.invoke(nrepl.clj:461)
	at nrepl.middleware$wrap_conj_descriptor$fn__803.invoke(middleware.clj:17)
	at cider.nrepl$wrap_macroexpand$fn__1624.invoke(nrepl.clj:268)
	at nrepl.middleware$wrap_conj_descriptor$fn__803.invoke(middleware.clj:17)
	at cider.nrepl$wrap_out$fn__1640.invoke(nrepl.clj:313)
	at nrepl.middleware$wrap_conj_descriptor$fn__803.invoke(middleware.clj:17)
	at nrepl.middleware.session$session$fn__1234.invoke(session.clj:197)
	at nrepl.middleware$wrap_conj_descriptor$fn__803.invoke(middleware.clj:17)
	at cider.nrepl$wrap_slurp$fn__1548.invoke(nrepl.clj:118)
	at nrepl.middleware$wrap_conj_descriptor$fn__803.invoke(middleware.clj:17)
	at nrepl.server$handle_STAR_.invokeStatic(server.clj:18)
	at nrepl.server$handle_STAR_.invoke(server.clj:15)
	at nrepl.server$handle$fn__1271.invoke(server.clj:27)
	at clojure.core$binding_conveyor_fn$fn__5739.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(java.base@11.0.1/FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.1/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.1/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.1/Thread.java:834)
```

To workaround the issue I have commented out the "complete" line from handle-complete:

```clojure
(defn handle-complete [handler msg]
  (with-safe-transport handler msg
    ;;"complete" complete-reply
    "complete-doc" doc-reply
    "complete-flush-caches" flush-caches-reply))
```

### cider-nrepl version

;; CIDER 0.21.0snapshot (package: 20190116.1142), nREPL 0.5.3
;; Clojure 1.10.0, Java 11.0.1

### Java version

11.0.1

### Operating system

Mac OS X 10.14.2

**Comment by bbatsov** [comment]
Sounds like a job for @alexander-yakushev. :-)

**Comment by jekyllislandtours** [comment]
I am not sure if started after I typed the ':' I think it was after I typed the '/' following the namespace with a lot of keywords in it.

Hard limiting seems reasonable. I would think 1000 would not be an issue.

**Comment by bbatsov** [comment]
Judging from the conversation in #599 it seems that @alexander-yakushev plans to fix this directly in compliment, so I'll close this ticket.
