### ISSUE TITLE
lein repl fails to load

### ISSUE THREAD

**Issue by babysnakes** [clojure-emacs/cider-nrepl#91]
(Sorry for not having time to invest in solving it myself but I'm currently under a very tight schedule :( )

When using the latest version (from github or repository) I get the following error when running `lein repl`:

``` sh
rror loading cider.nrepl.middleware.classpath: java.lang.Exception: Unable to resolve symbol: response-for in this context (classpath.clj:12)
WARNING: doc already refers to: #'clojure.core/doc in namespace: compliment.sources.ns-mappings, being replaced by: #'compliment.sources.ns-mappings/doc
WARNING: doc already refers to: #'clojure.core/doc in namespace: compliment.sources.namespaces-and-classes, being replaced by: #'compliment.sources.namespaces-and-classes/doc
Error loading cider.nrepl.middleware.complete: java.lang.Exception: Unable to resolve symbol: response-for in this context (complete.clj:28)
Error loading cider.nrepl.middleware.info: java.io.FileNotFoundException: Could not locate clojure/reflect__init.class or clojure/reflect.clj on classpath:  (java.clj:1)
Error loading cider.nrepl.middleware.inspect: java.lang.Exception: Unable to resolve symbol: ->MapDependencyGraph in this context (dependency.clj:93)
Error loading cider.nrepl.middleware.macroexpand: java.lang.Exception: Unable to resolve symbol: response-for in this context (macroexpand.clj:25)
Error loading cider.nrepl.middleware.resource: java.lang.Exception: Unable to resolve symbol: response-for in this context (resource.clj:13)
Error loading cider.nrepl.middleware.stacktrace: java.lang.Exception: No such var: repl/demunge (stacktrace.clj:31)
Error loading cider.nrepl.middleware.test: java.lang.Exception: No such var: repl/demunge (stacktrace.clj:31)
Error loading cider.nrepl.middleware.trace: java.lang.Exception: Unable to resolve symbol: response-for in this context (trace.clj:14)
Exception in thread "main" java.lang.Exception: Unable to resolve var: cider.nrepl.middleware.classpath/wrap-classpath in this context (form-init1041045194153155143.clj:1)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:5376)
    at clojure.lang.Compiler.analyze(Compiler.java:5190)
    at clojure.lang.Compiler.analyze(Compiler.java:5151)
    at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3057)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:5371)
    at clojure.lang.Compiler.analyze(Compiler.java:5190)
    at clojure.lang.Compiler.analyze(Compiler.java:5151)
    at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3057)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:5371)
    at clojure.lang.Compiler.analyze(Compiler.java:5190)
    at clojure.lang.Compiler.access$100(Compiler.java:35)
    at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:4921)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:5369)
    at clojure.lang.Compiler.analyze(Compiler.java:5190)
    at clojure.lang.Compiler.analyze(Compiler.java:5151)
    at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:4670)
    at clojure.lang.Compiler$FnMethod.parse(Compiler.java:4328)
    at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3173)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:5367)
    at clojure.lang.Compiler.analyze(Compiler.java:5190)
    at clojure.lang.Compiler.eval(Compiler.java:5421)
    at clojure.lang.Compiler.eval(Compiler.java:5415)
    at clojure.lang.Compiler.load(Compiler.java:5857)
    at clojure.lang.Compiler.loadFile(Compiler.java:5820)
    at clojure.main$load_script.invoke(main.clj:221)
    at clojure.main$init_opt.invoke(main.clj:226)
    at clojure.main$initialize.invoke(main.clj:254)
    at clojure.main$null_opt.invoke(main.clj:279)
    at clojure.main$main.doInvoke(main.clj:354)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:369)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:482)
    at clojure.main.main(main.java:37)
Caused by: java.lang.Exception: Unable to resolve var: cider.nrepl.middleware.classpath/wrap-classpath in this context
    at clojure.lang.Compiler$TheVarExpr$Parser.parse(Compiler.java:560)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:5369)
    ... 33 more
```

Thanks in advance

**Comment by roncodingenthusiast** [comment]
I had the same error when I tried using clojure 1.7 and seesaw 1.4.2. All I did to fix it was to use the latest version of seesaw (1.4.5 that his time)
